services:
  jekyll:
    build:
      context: .
      args:
        MODE: dev
    container_name: jekyll-dev
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./_site:/srv/jekyll/_site  # map _site so you can inspect output
    environment:
      MODE: dev
    command: /bin/bash /srv/jekyll/entrypoint.sh
